#!/usr/bin/env node
var net = require('net');

if(process.argv[2] && process.argv[3]){
  var appName = process.argv[2];  //应用名
  var action = process.argv[3]; //操作
  var command;  //发送的命令
  switch(action){
    case "start":
    case "restart":
    case "stop":
    case "status":
      command = action + " " + appName + "\n";
      break;
    case "stdout":
    case "stderr":
      var line = process.argv[4] || '10';
      command = action + " " + appName + " " + line + "\n";
      break;
    default:
      console.log("Error: undefined command!\nPlease enter the right command!");
      return;
  }

  var socket = net.createConnection(1128);

  console.log("sending command...");
  socket.write(command);
  socket.on('data', function(data){
    //消除上面一行，即sending command...这句
    //something
    data = "" + data;
    if(action != "stdout" && action != "stderr"){
      data = eval('('+data+')');
    }
    if(data.status == "error"){ //没有成功执行则输出错误信息
      console.log("Error: " + data.msg);
    }
    else{
      if(data.msg){ //start stop restart成功时输出成功的信息
        console.log(data.msg);
      }
      else if(action == "status"){  //如果是取status，则把收到的状态值一一输出
        console.log("status of " + appName + ": ");
        for(var status in data){
          console.log("\t" + status + ": " + data[status]);
        }
      }
      else{ //stdout stderr的data直接输出
        console.log(data);
      }
    }
    socket.end(); //销毁socket
  });
}
else{ //如果参数不齐全，提示输入格式错误
  console.log("Error: incorrect format");
  console.log("Please enter: cnae [appName] [action]");
}
