#!/usr/bin/env node
var net = require('net');

if(process.argv[2] && process.argv[3]){
  var appName = process.argv[2];
  var action = process.argv[3];
  var command;
  switch(action){
    case "start":
    case "restart":
    case "stop":
    case "status":
      command = action + " " + appName + "\n";
      break;
    case "stdout":
    case "stderr":
      var line = process.argv[4] || '10';
      command = action + " " + appName + " " + line + "\n";
      break;
    default:
      console.log("error: undefined command!\nPlease enter the right command!");
      return;
  }

  var socket = new net.Socket();

  socket.connect(1128);

  console.log("sending command...");
  socket.write(command);
  socket.on('data', function(data){
    data = "" + data;
    if(action != "stdout" && action != "stderr"){
      data = eval('('+data+')');
    }
    if(data.status == "error"){ //没有成功执行则输出错误信息
      console.log("error: " + data.msg);
    }
    else{
      if(data.msg){ //start stop restart成功时输出成功的信息
        console.log(data.msg);
      }
      else if(action == "status"){  //如果是取status，则把收到的状态值一一输出
        console.log("status of " + appName + ": ");
        for(var status in data){
          console.log("\t" + status + ": " + data[status]);
        }
      }
      else{ //stdout stderr的data直接输出
        console.log(data);
      }
    }
    socket.destroy(); //销毁socket
  });
}
else{
  console.log("Error: incorrect format");
  console.log("Please enter: cnae [appName] [action]");
}
